[package]
name = "minimize"
version = "0.1.0"
edition = "2021"

[dependencies]
wayfire-rs = "0.2.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
