[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
wayfire-rs = "0.1.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

